name: Documentation Issue
description: Report documentation errors, discrepancies, or suggest improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |-
        Thanks for helping improve our documentation! Please provide details about the documentation issue you've found.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Spelling/Grammar error
        - Technical inaccuracy
        - Missing information
        - Outdated content
        - Broken link
        - Unclear explanation
        - Code example error
        - Formatting issue
        - Other
    validations:
      required: true

  - type: dropdown
    id: location
    attributes:
      label: Documentation Location
      description: Where did you find this issue?
      options:
        - Wiki
        - README.md
        - API Documentation
        - Code comments/docstrings
        - CONTRIBUTING.md
        - Configuration guides
        - Deployment guides
        - Issue/PR templates
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL or File Path
      description: Link to the wiki page or path to the file with the issue
      placeholder: "https://github.com/authify/authify/wiki/Page-Name or path/to/file.md"
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: Copy the incorrect or problematic text here
      placeholder: "The current documentation says..."
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: How should this be corrected or improved?
      placeholder: "It should say... or It should include..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information or screenshots
      placeholder: "This is confusing because... or See screenshot..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to submit a PR to fix this documentation issue
