import Config

# Set the runtime environment (used instead of Mix.env() which isn't available in releases)
config :authify, env: :prod

# Mark the session cookie `Secure` in production. TLS terminates at the
# CDN/ingress in front of the app, so the cookie should only ever be sent
# over HTTPS. Plain-HTTP production deployments must set this to false, or
# sessions will not work. This is a compile-time setting because Plug.Session
# options are baked into the endpoint at compile time.
config :authify, :session_secure, true

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :authify, AuthifyWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
