defmodule AuthifyWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :authify

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  #
  # `:secure` is enabled in production so the session cookie is only ever
  # sent over HTTPS (TLS terminates at the CDN/ingress in front of the app).
  # It is disabled in dev/test and plain-HTTP deployments, where a Secure
  # cookie would never be sent and sessions would not work.
  @session_options [
    store: :cookie,
    key: "_authify_key",
    signing_salt: "afgN/h7v",
    same_site: "Lax",
    secure: Application.compile_env(:authify, :session_secure, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  #
  # `only_matching` is required for top-level files that get digested
  # (e.g. `favicon-<hash>.svg`); `only` matches path segments exactly and
  # therefore never matches the digested filename. Directory prefixes
  # (`assets`, `images`, `fonts`) are already covered by `only`.
  plug Plug.Static,
    at: "/",
    from: :authify,
    gzip: not code_reloading?,
    only: AuthifyWeb.static_paths(),
    only_matching: AuthifyWeb.static_match_prefixes(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :authify
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug AuthifyWeb.Router
end
